### PR TITLE
Always use linear colorX to calculate Luminance

### PR DESCRIPTION
**Pull request by Banane9**
Adds a fix for https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/281

### CODE REVIEW

**Comment by Nytra** [comment]
Why don't you use `Enabled` inside of the patch?

**Comment by Banane9** [comment]
Hmmm, done all of these like this ... but could be changed. But for these I mainly see the toggle a something for disabling the fix if it gets implemented.

**Comment by Nytra** [comment]
Should it always be converting to ColorProfile.Linear ?

**Comment by Banane9** [comment]
Well, that's what the Luminance calculation is based on 
```cs
public float Luminance => 0.2126f * r + 0.7152f * g + 0.0722f * b;
```

**Review by Nytra — APPROVED** [review]

**Pull request merged**
